cookie:
  expiry_days: 30
  key: random_key
  name: app_cookie
credentials:
  usernames:
    admin:
      name: Admin
      password: asdzxc
    user123:
      name: Arjun xyzzy
      password: $2b$12$LfBe39L5OAW6ZRDtMdhtnOb/AB0EwwknhfninxpET8b/VEsHznPUO
